env:
  es6: true
  browser: true
  webextensions: true
extends:
  - plugin:vue/base
  - plugin:vuetify/base
parserOptions:
  parser: babel-eslint
  ecmaVersion: 8
  sourceType: module
rules:
  no-console: 0
  linebreak-style: 'off'
  array-bracket-spacing: ['error', 'never']
  vuetify/no-deprecated-colors: [ 'error', {
    themeColors: [ 'tertiary' ]
  } ]
globals:
  DEBUG: true
  PRODUCTION: true
  MOZ: true
  ga: true
